Adds highlights to projects response
patch-technology/patch-node pull request #51
Opened 2021-11-08 19:27 UTC by alianam

### What

Adds `highlights` to projects response.

### SDK Release Checklist

- [ ] Have you added an integration test for the changes?
- [ ] Have you built the package locally and made queries against it successfully?
- [ ] Did you update the changelog?
- [ ] Did you bump the package version?
- [ ] For breaking changes, did you plan for the release of the new SDK versions and deploy the API to production?

2021-11-09 02:45 UTC, kleinjm commented on test/integration/projects.test.js
> +    expect(projectResponse.data.highlights).to.be.a('array');
[nit] does 
```suggestion
    expect(projectResponse.data.highlights).to.be.an('array');
```
work?

2021-11-09 02:45 UTC, kleinjm requested changes
Let's see if you can fix the diff on the `package-lock.json`. Otherwise, this LGTM

2021-11-09 22:59 UTC, alianam commented on test/integration/projects.test.js
> +    expect(projectResponse.data.highlights).to.be.a('array');
Yes it does!

2021-11-10 17:00 UTC, pcothenet approved these changes
Nice!

2021-11-11 16:07 UTC, kleinjm approved these changes

2021-11-12 15:36 UTC, kleinjm approved these changes
LGTM. Failing test doesn't seem related

2021-11-12 16:42 UTC, pcothenet approved these changes

2021-11-15 18:56 UTC, merged